# Use the official NGINX image as the base image
FROM nginx:alpine

# Copy your custom NGINX configuration into the container
COPY ApiGateway/conf/apigateway.conf /etc/nginx/conf.d/default.conf

# Copy static frontend files to the default NGINX HTML directory
COPY ../../frontend /usr/share/nginx/html

# Expose port 8080 for the gateway
EXPOSE 8080

# Start NGINX when the container launches
CMD ["nginx", "-g", "daemon off;"]
