# Basisimage verwenden
FROM nginx:alpine

# Standard-nginx.conf entfernen
RUN rm /etc/nginx/nginx.conf

# Eigene NGINX-Konfiguration kopieren
COPY ApiGateway/conf/apigateway.conf /etc/nginx/nginx.conf

# Statische Frontend-Dateien kopieren
COPY ../../frontend /usr/share/nginx/html

# Port 8080 freigeben
EXPOSE 8080

# NGINX starten
CMD ["nginx", "-g", "daemon off;"]
