version: '3.9'

services:
  auth-service:
    build:
      context: ./authentification-service/authentification-service
      dockerfile: Dockerfile.auth
    container_name: auth-service
    ports:
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  calc-service:
    build:
      context: ./calculation-service/calculation-service
      dockerfile: Dockerfile.calc
    container_name: calc-service
    ports:
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  grade-service:
    build:
      context: ./grade-service/grade-service
      dockerfile: Dockerfile.grade
    container_name: grade-service
    ports:
      - "5003:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5004:8081"

  nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "8080:8080"
  volumes:
    - ./ApiGateway/conf/apigateway.conf:/etc/nginx/nginx.conf
    - ./frontend/build:/usr/share/nginx/html
  depends_on:
    - auth-service
    - calc-service
    - grade-service
    - frontend


