version: '3.9'

services:
  logging:
    build:
      context: ./logs
      dockerfile: Dockerfile.logging
    container_name: logging-service
    volumes:
      - gradesystem_logs:/var/log/gradesystem

  auth-service:
    build:
      context: ./authentification-service/authentification-service
      dockerfile: Dockerfile.auth
    container_name: auth-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    volumes:
      - gradesystem_logs:/var/log/gradesystem
    depends_on:
      - logging

  calc-service:
    build:
      context: ./calculation-service/calculation-service
      dockerfile: Dockerfile.calc
    container_name: calc-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    volumes:
      - gradesystem_logs:/var/log/gradesystem
    depends_on:
      - logging

  grade-service:
    build:
      context: ./grade-service/grade-service
      dockerfile: Dockerfile.grade
    container_name: grade-service
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    volumes:
      - gradesystem_logs:/var/log/gradesystem
    depends_on:
      - logging

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5004:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./ApiGateway/conf/apigateway.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - auth-service
      - calc-service
      - grade-service
      - frontend

volumes:
  gradesystem_logs:
