apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculation-service
  namespace: mynetwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculation-service
  template:
    metadata:
      labels:
        app: calculation-service
    spec:
      containers:
      - name: calculation-service
        image: kurizakii/calc-service:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: calculation-service
  namespace: mynetwork
spec:
  selector:
    app: calculation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
