apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-service
  namespace: mynetwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-service
  template:
    metadata:
      labels:
        app: calc-service
    spec:
      containers:
      - name: calc-service
        image: kurizakii/calc-service:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
  namespace: mynetwork
spec:
  selector:
    app: calc-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
