apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service
  namespace: mynetwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-service
  template:
    metadata:
      labels:
        app: grade-service
    spec:
      containers:
      - name: grade-service
        image: kurizakii/grade-service:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: grade-service
  namespace: mynetwork
spec:
  selector:
    app: grade-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
