############################################
# DEPLOYMENT: grade-service
# This Deployment runs the grade-service within the "mynetwork" namespace.
# It starts with 2 replicas, each labeled "app: grade-service".
# Resource requests and limits specify the minimum/maximum CPU and memory.
############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service
  namespace: mynetwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-service
  template:
    metadata:
      labels:
        app: grade-service
    spec:
      containers:
        - name: grade-service
          image: kurizakii/grade-service:latest
          resources:
            requests:
              cpu: 100m         # Minimum CPU requested
              memory: 200Mi     # Minimum Memory requested
            limits:
              cpu: 500m         # Maximum CPU allowed
              memory: 512Mi     # Maximum Memory allowed
          ports:
            - containerPort: 8080  # Container port

---
############################################
# SERVICE: grade-service
# Exposes the grade-service Pods on port 8080 internally within the "mynetwork" namespace.
# The "selector" field directs traffic to Pods labeled "app: grade-service".
############################################
apiVersion: v1
kind: Service
metadata:
  name: grade-service
  namespace: mynetwork
spec:
  selector:
    app: grade-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
############################################
# HORIZONTAL POD AUTOSCALER: grade-service-hpa
# Automatically scales the number of Pods for the "grade-service" Deployment
# based on CPU utilization. Here, it will try to keep CPU usage at 50%.
# - minReplicas: 2 (will not scale below 2 replicas)
# - maxReplicas: 5 (will not scale above 5 replicas)
############################################
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grade-service-hpa
  namespace: mynetwork
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grade-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
