apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calculation-service-hpa
  namespace: mynetwork
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculation-service
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
