apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: mynetwork
spec:
  selector:
    app: kibana
  ports:
    - name: web
      protocol: TCP
      port: 5601
      targetPort: 5601
  type: ClusterIP
