############################################
# NAMESPACE: mynetwork
# This creates a logical grouping (namespace) within the cluster
# called "mynetwork". All objects created in this namespace
# will be isolated from other namespaces in terms of naming.
############################################
apiVersion: v1
kind: Namespace
metadata:
  name: mynetwork
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-mynetwork
  namespace: mynetwork
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
