apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mynetwork
spec:
  selector:
    app: prometheus
  ports:
    - name: web
      protocol: TCP
      port: 9900
      targetPort: 9900
  type: ClusterIP
