global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9900']

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'calc-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['calc-service:8080']

  - job_name: 'grade-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['grade-service:8080']

  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8080']
