global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'grade-system'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names: [mynetwork, logging, monitoring]
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    action: keep
    regex: (auth-service|calc-service|grade-service|api-gateway|elasticsearch|kibana|prometheus)
  metrics_path: /metrics
  scheme: http
  scrape_interval: 15s
  scrape_timeout: 10s

- job_name: 'elasticsearch'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names: [logging]
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    action: keep
    regex: elasticsearch
  metrics_path: /_prometheus/metrics
  scheme: http

- job_name: 'kibana'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names: [logging]
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    action: keep
    regex: kibana
  metrics_path: /api/status
  scheme: http

- job_name: 'kubernetes-apiservers'
  kubernetes_sd_configs:
  - role: endpoints
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: default;kubernetes;https
