# Define the host address variable for the grade service
@grade_service_HostAddress = http://localhost:5035

# Send a GET request to the /weatherforecast/ endpoint of the grade service
GET {{grade_service_HostAddress}}/weatherforecast/
Accept: application/json
