name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-outdated tool
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Update NuGet Packages
      run: |
        for csproj in $(find . -name '*.csproj' -type f | grep -v 'Backup'); do
          echo "Updating dependencies for $csproj"
          dotnet outdated --upgrade "$csproj"
        done

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update dependencies'
        git push
