name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Images
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd microservice-based-grade-management
            git pull origin main
            kubectl apply -f k8s/ --recursive
            kubectl rollout status deployment/auth-service -n mynetwork
            kubectl rollout status deployment/calc-service -n mynetwork
            kubectl rollout status deployment/grade-service -n mynetwork

      # Step 3: Deploy Prometheus to Kubernetes
      - name: Deploy Prometheus to Kubernetes
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd microservice-based-grade-management/k8s
            kubectl apply -f prometheus.yml
