name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  docker-deploy:
    name: Docker Compose Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Docker Compose
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          timeout: 60s  
          command_timeout: 600s
          script: |
              cd microservice-based-grade-management &&
              git pull origin main &&
              docker-compose pull &&
              docker-compose down &&
              docker-compose up -d

  k3s-deploy:
    name: k3s Deployment
    needs: docker-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: Deploy to k3s
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          timeout: 60s  
          command_timeout: 600s
          script: |
              cd microservice-based-grade-management &&
              echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig &&
              export KUBECONFIG=/etc/rancher/k3s/k3s.yaml &&
              kubectl apply -f ./k8s/namespace.yml --validate=false &&
              kubectl apply -f ./k8s/ --validate=false
