name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Debug - List all .csproj files
      run: |
        find . -name '*.csproj' -type f

    - name: Restore dependencies for all projects
      run: |
        for csproj in $(find . -name '*.csproj' -type f | grep -v 'Backup'); do
          echo "Restoring $csproj"
          dotnet restore "$csproj"
        done

    - name: Build all projects
      run: |
        for csproj in $(find . -name '*.csproj' -type f | grep -v 'Backup'); do
          echo "Building $csproj"
          dotnet build "$csproj" --no-restore
        done

    - name: Run tests for all projects
      run: |
        for csproj in $(find . -name '*.csproj' -type f | grep -v 'Backup'); do
          echo "Testing $csproj"
          dotnet test "$csproj" --no-build --verbosity normal
        done
