name: Deploy Prometheus to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/prometheus-deployment.yaml'
      - 'k8s/prometheus.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy Prometheus
        run: |
          kubectl apply -f prometheus-deployment.yaml
          kubectl apply -f prometheus.yml
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
